### ISSUE TITLE
Does not work properly on many games

### ISSUE THREAD

**Issue by 0li0li** [brussell1/Shaders#4]
Hi, I love this fx, it's in fact the main reason I use Reshade, since I have poor vision and need to often zoom in the healthbar or subtitles, but it is quite hit or miss... Not sure why, maybe it fails on Dx11 games specifically, but many games I try and activate areacopy.fx I end up with the entire screen flashing, as if it was zooming on a single pixel (I suspect in the top left of the screen).

None of the sliders do anything to fix this, and changing depth buffers settings don't seem to help either. I could not find anything only, so I wonder if you could provide some insight on the matter.

Thanks and keep up the great work!

**Comment by brussell1** [comment]
Fixed in https://github.com/brussell1/Shaders/commit/e2f11ce64070d248af481493b08206cfd0dc9147.

**Comment by 0li0li** [comment]
FYI, turning the Dx11 game to Dx9 made AreaCopy work (even before setting Reshade to Dx9 for said game). Thanks for the quick update btw :D

**Comment by 0li0li** [comment]
Reporting back after testing: works well on Dx9 and Dx11, great job!
