### ISSUE TITLE
Area discard edges Fullscreen vs Window?

### ISSUE THREAD

**Issue by 2mg** [brussell1/Shaders#6]
When switching between these modes (or anything that changes screen size), the edges are absolute from that screen size.

Since it's good for setting up discarded areas in Fullscreen, it doesn't translate well into Windowed modes.

Is it possible to detect these changes and disable discarding if the screen size is smaller or dynamically adjust edge sizes?

Basically an "inside window", if discarded edges would get into that area, don't apply them for example?

**Comment by brussell1** [comment]
Added a relative mode with https://github.com/brussell1/Shaders/commit/15a3655baf31fbac0218c216a74299a2bce5cfc3.
